apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/openstack-k8s-operators/cinder-operator/config/samples/backends/lvm/nvme-tcp
patches:
- target:
    kind: OpenStackControlPlane
    name: openstack
  patch: |-
    - op: replace
      path: /spec/nova/template/apiServiceTemplate/customServiceConfig
      value: |
        [pci]
        alias = { "vendor_id":"${VENDOR_ID}", "product_id":"${PRODUCT_ID}", "device_type":"type-PCI", "name":"nvidia", "numa_policy":"preferred" }
